apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-melding-om-vedtak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling
        - application: dp-saksbehandling-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: nais
        - application: azure-token-generator
          namespace: nais
        {{/if}}
    outbound:
      external:
        - host: rt6o382n.api.sanity.io
      rules:
        - application: dp-behandling
          namespace: teamdagpenger
        - application: dp-saksbehandling
          namespace: teamdagpenger
        - application: logging
          namespace: nais-system
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
    - name: GRUPPE_SAKSBEHANDLER
      value: "{{ azure.grupper.saksbehandler }}"
    - name: DP_BEHANDLING_API_SCOPE
      value: "{{ DP_BEHANDLING_API_SCOPE }}"
    - name: DP_SAKSBEHANDLING_API_SCOPE
      value: "{{ DP_SAKSBEHANDLING_API_SCOPE }}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: "{{ azure.tenant }}"
      claims:
        groups:
          - id: "{{ azure.grupper.saksbehandler }}"
        extra:
          - NAVident
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: vedtaksmelding-v1
        diskAutoresize: true
        diskType: SSD
        highAvailability: {{ db.highAvailability }}
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: {{ db.pointInTimeRecovery }}
        tier: "{{ db.tier }}"
        type: POSTGRES_16
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
