openapi: 3.0.3
info:
  title: Melding om vedtak API
  version: 1.0.0
  description: Et API for å hente ut brevblokker som utgjør melding om vedtak.
paths:
  /melding-om-vedtak/{behandlingId}:
    get:
      summary: Hent brevblokkIder og korresponderende opplysninger som utgjør melding om vedtak
      description: Henter melding om vedtak for en gitt behandlingId
      parameters:
        - name: behandlingId
          in: path
          description: id for behandling
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MeldingOmVedtak'
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
  /melding-om-vedtak/{behandlingId}/{brevblokkId}/utvidet-beskrivelse:
    put:
      summary: Lagrer utvidet beskrivelse for en gitt brevblokk i meldingen om vedtak
      parameters:
        - in: path
          name: behandlingId
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: brevblokkId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: Utvidet beskrivelse som skal inngå i vedtaksmeldingen
      responses:
        '200':
          description: Utvidet beskrivelse for brevblokk er lagret og returnerer sistEndretTidspunkt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetBeskrivelseSistEndretTidspunkt'
        '400':
          description: ContentType må være text/plain
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'


components:
  schemas:
    UtvidetBeskrivelseSistEndretTidspunkt:
      type: object
      properties:
        sistEndretTidspunkt:
          type: string
          format: date-time
          description: Tidspunkt utvidet beskrivelse sist ble endret

    MeldingOmVedtak:
      type: object
      properties:
        brevblokkIder:
          type: array
          items:
            type: string
        opplysninger:
          type: array
          items:
            $ref: '#/components/schemas/Opplysning'
        utvidedeBeskrivelser:
          type: array
          items:
            $ref: '#/components/schemas/UtvidetBeskrivelse'

    UtvidetBeskrivelse:
      type: object
      properties:
        brevblokkId:
          type: string
        tekst:
          type: string
        sistEndretTidspunkt:
          type: string
          format: date-time

    Opplysning:
      type: object
      properties:
        tekstId:
          type: string
        verdi:
            type: string
        datatype:
          type: string

    HttpProblem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string