openapi: 3.0.3
info:
  title: Melding om vedtak API
  version: 1.0.0
  description: Et API for å håndtere det å lage brev i dp-sak
servers:
  - url: https://dp-melding-om-vedtak.intern.dev.nav.no
    description: dev
  - url: https://dp-melding-om-vedtak.intern.nav.no
    description: prod
paths:
  /melding-om-vedtak/{behandlingId}/brev-variant:
    put:
      summary: Lagrer brev-variant for behandling
      description: Lagrer brev-variant for behandling, slik at dette kan hentes når brev skal produseres som forhåndsvisning eller endelig brev.
      security:
        - azureAd: [ ]
      parameters:
        - name: behandlingId
          in: path
          description: id for behandling
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrevVariantRequest'
      responses:
        '204':
          description: Brev-variant er lagret
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        default:
          description: Feil
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

  /melding-om-vedtak/{behandlingId}/html:
    post:
      summary: Hent vedtak som HTML for en gitt behandlingId
      description: Henter HTML for en gitt behandlingId. Henter alltid nyeste Sanity innhold og behandling
      security:
        - azureAd: [ ]
      parameters:
        - name: behandlingId
          in: path
          description: id for behandling
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeldingOmVedtakData'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeldingOmVedtakResponse'
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        default:
          description: Feil
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

  /melding-om-vedtak/{behandlingId}/vedtaksmelding:
    post:
      summary: Henter endelig brev for en gitt behandling
      description: Henter endelig brev for en gitt behandling. Garanterer bruk av samme Sanity innhold som da brevet ble laget vha html-endepunktet.
      security:
        - azureAd: [ ]
      parameters:
        - name: behandlingId
          in: path
          description: id for behandling
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeldingOmVedtakData'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  html:
                    type: string
                    description: HTML for melding om vedtak
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        default:
          description: Feil
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

  /melding-om-vedtak/{behandlingId}/{brevblokkId}/utvidet-beskrivelse:
    put:
      summary: Lagrer utvidet beskrivelse for en gitt brevblokk i meldingen om vedtak
      security:
        - azureAd: [ ]
      parameters:
        - in: path
          name: behandlingId
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: brevblokkId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: Utvidet beskrivelse som skal inngå i vedtaksmeldingen
      responses:
        '200':
          description: Utvidet beskrivelse for brevblokk er lagret og returnerer sistEndretTidspunkt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetBeskrivelseSistEndretTidspunkt'
        '400':
          description: ContentType må være text/plain
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        default:
          description: Feil
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

  /melding-om-vedtak/{behandlingId}/{brevblokkId}/utvidet-beskrivelse-json:
    put:
      summary: Lagrer utvidet beskrivelse for en gitt brevblokk i meldingen om vedtak
      security:
        - azureAd: [ ]
      parameters:
        - in: path
          name: behandlingId
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: brevblokkId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtvidetBeskrivelseTekst'
      responses:
        '200':
          description: Utvidet beskrivelse for brevblokk er lagret og returnerer sistEndretTidspunkt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetBeskrivelseSistEndretTidspunkt'
        '400':
          description: ContentType må være text/plain
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        '404':
          description: Behandlingen finnes ikke
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'
        default:
          description: Feil
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

components:
  schemas:
    UtvidetBeskrivelseTekst:
      type: object
      properties:
        tekst:
          type: string
          description: Utvidet beskrivelse som skal inngå i vedtaksmeldingen
      required:
        - tekst

    UtvidetBeskrivelseSistEndretTidspunkt:
      type: object
      properties:
        sistEndretTidspunkt:
          type: string
          format: date-time
          description: Tidspunkt utvidet beskrivelse sist ble endret

    MeldingOmVedtakResponse:
      type: object
      properties:
        html:
          type: string
          description: HTML for melding om vedtak
        utvidedeBeskrivelser:
          type: array
          items:
            $ref: '#/components/schemas/UtvidetBeskrivelse'
        brevVariant:
          $ref: '#/components/schemas/BrevVariant'
      required:
        - html
        - utvidedeBeskrivelser
        - brevVariant

    UtvidetBeskrivelse:
      type: object
      properties:
        brevblokkId:
          type: string
        tekst:
          type: string
        sistEndretTidspunkt:
          type: string
          format: date-time
        tittel:
          type: string
      required:
        - brevblokkId
        - tekst
        - tittel

    BrevVariantRequest:
      type: object
      properties:
        brevVariant:
          $ref: '#/components/schemas/BrevVariant'
      required:
        - brevVariant

    MeldingOmVedtakData:
      type: object
      properties:
        sakId:
          type: string
        behandlingstype:
          $ref: '#/components/schemas/Behandlingstype'
        fornavn:
          type: string
        mellomnavn:
          type: string
        etternavn:
          type: string
        fodselsnummer:
          type: string
          pattern: '^[0-9]{11}$'
          description: "Må være et gyldig fødselsnummer med nøyaktig 11 sifre."
        saksbehandler:
          $ref: '#/components/schemas/Behandler'
        beslutter:
          $ref: '#/components/schemas/Behandler'
      required:
        - behandlingstype
        - fornavn
        - etternavn
        - fodselsnummer
        - saksbehandler

    Behandler:
      type: object
      properties:
        fornavn:
          type: string
        etternavn:
          type: string
        ident:
          type: string
        enhet:
          type: object
          properties:
            navn:
              type: string
            enhetNr:
              type: string
            postadresse:
              type: string
          required:
            - navn
            - postadresse
      required:
        - fornavn
        - etternavn
        - enhet

    BrevVariant:
      type: string
      default: "GENERERT"
      enum:
        - "GENERERT"
        - "EGENDEFINERT"

    Behandlingstype:
      type: string
      enum:
        - "RETT_TIL_DAGPENGER"
        - "SØKNAD"
        - "KLAGE"
        - "MELDEKORT"
        - "MANUELL"

    HttpProblem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string

  securitySchemes:
    azureAd:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [AzureAD](https://docs.nais.io/security/auth/azure-ad) til autentisering. 
        Token må ha `audience` satt til `[cluster].teamdagpenger.dp-melding-om-vedtak`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp.teamdagpenger.dp-melding-om-vedtak)
